FROM debian:bookworm-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates libssl3 \
    && rm -rf /var/lib/apt/lists/*

COPY proxy /usr/local/bin/proxy

ENTRYPOINT ["/usr/local/bin/proxy"]
