apiVersion: v1
kind: ConfigMap
metadata:
  name: pageserver-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "lakeon.labels" . | nindent 4 }}
data:
  pageserver.toml: |
    listen_pg_addr = '0.0.0.0:{{ .Values.pageserver.pgPort }}'
    listen_http_addr = '0.0.0.0:{{ .Values.pageserver.httpPort }}'
    broker_endpoint = 'http://storage-broker:{{ .Values.storageBroker.port }}'
    control_plane_api = 'http://lakeon-api:{{ .Values.api.port }}'
    control_plane_emergency_mode = true
    pg_distrib_dir = '/usr/local'

    [remote_storage]
    {{- if .Values.obs.usePathStyle }}
    endpoint = '{{ .Values.obs.endpoint }}'
    {{- end }}
    bucket_name = '{{ .Values.obs.bucket }}'
    bucket_region = '{{ .Values.obs.region }}'
    prefix_in_bucket = '/pageserver'
  identity.toml: |
    id = 1
