{{- if .Values.obs.accessKey }}
apiVersion: v1
kind: Secret
metadata:
  name: obs-credentials
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "lakeon.labels" . | nindent 4 }}
type: Opaque
data:
  access-key: {{ .Values.obs.accessKey | b64enc | quote }}
  secret-key: {{ .Values.obs.secretKey | b64enc | quote }}
{{- end }}
