apiVersion: v1
kind: Secret
metadata:
  name: api-credentials
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "lakeon.labels" . | nindent 4 }}
type: Opaque
data:
  proxy-token: {{ default "" .Values.api.proxyToken | b64enc | quote }}
  db-password: {{ .Values.metadataDb.password | b64enc | quote }}
  admin-token: {{ default "" .Values.api.adminToken | b64enc | quote }}
