{{- if include "lakeon.dataPlaneEnabled" . }}
apiVersion: v1
kind: Service
metadata:
  name: pageserver
  namespace: {{ .Values.global.namespace }}
  labels:
    app: pageserver
    {{- include "lakeon.labels" . | nindent 4 }}
  {{- if or (and .Values.pageserver.elb .Values.pageserver.elb.id) (and .Values.pageserver.elb .Values.pageserver.elb.autocreate) }}
  annotations:
    {{- if .Values.pageserver.elb.id }}
    kubernetes.io/elb.id: {{ .Values.pageserver.elb.id | quote }}
    {{- end }}
    kubernetes.io/elb.class: {{ .Values.pageserver.elb.class | default "union" | quote }}
    {{- if .Values.pageserver.elb.autocreate }}
    kubernetes.io/elb.autocreate: {{ .Values.pageserver.elb.autocreate | quote }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.pageserver.serviceType | default "ClusterIP" }}
  selector:
    app: pageserver
  ports:
    - name: http
      port: {{ .Values.pageserver.httpPort }}
      targetPort: http
    - name: pg
      port: {{ .Values.pageserver.pgPort }}
      targetPort: pg
{{- end }}
