apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: {{ .Values.global.namespace }}
  labels:
    app: proxy
    {{- include "lakeon.labels" . | nindent 4 }}
  {{- if and .Values.proxy.elb .Values.proxy.elb.id }}
  annotations:
    kubernetes.io/elb.id: {{ .Values.proxy.elb.id | quote }}
    kubernetes.io/elb.class: {{ .Values.proxy.elb.class | default "union" | quote }}
  {{- end }}
spec:
  type: {{ .Values.proxy.serviceType | default "LoadBalancer" }}
  selector:
    app: proxy
  ports:
    - name: pg
      port: {{ .Values.proxy.listenPort }}
      targetPort: pg
    - name: http
      port: {{ .Values.proxy.httpPort }}
      targetPort: http
