{{- if and (include "lakeon.controlPlaneEnabled" .) (not .Values.api.split.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: lakeon-api
  namespace: {{ .Values.global.namespace }}
  labels:
    app: lakeon-api
    {{- include "lakeon.labels" . | nindent 4 }}
  {{- if or (and .Values.api.elb .Values.api.elb.id) (and .Values.api.elb .Values.api.elb.autocreate) }}
  annotations:
    {{- if .Values.api.elb.id }}
    kubernetes.io/elb.id: {{ .Values.api.elb.id | quote }}
    {{- end }}
    kubernetes.io/elb.class: {{ .Values.api.elb.class | default "union" | quote }}
    {{- if .Values.api.elb.autocreate }}
    kubernetes.io/elb.autocreate: {{ .Values.api.elb.autocreate | quote }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.api.serviceType }}
  selector:
    app: lakeon-api
  ports:
    - name: https
      port: {{ if and .Values.api.elb .Values.api.elb.port }}{{ .Values.api.elb.port }}{{ else }}{{ .Values.api.port | default 8080 }}{{ end }}
      targetPort: http
    - name: http-internal
      port: {{ .Values.api.internalPort | default 8088 }}
      targetPort: http-internal
{{- end }}
