apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: {{ .Values.global.namespace }}
  labels:
    app: proxy
    {{- include "lakeon.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  selector:
    app: proxy
  ports:
    - name: pg
      port: {{ .Values.proxy.listenPort }}
      targetPort: pg
    - name: http
      port: {{ .Values.proxy.httpPort }}
      targetPort: http
