apiVersion: v1
kind: Service
metadata:
  name: lakeon-api
  namespace: {{ .Values.global.namespace }}
  labels:
    app: lakeon-api
    {{- include "lakeon.labels" . | nindent 4 }}
  {{- if .Values.api.elb }}
  annotations:
    kubernetes.io/elb.id: {{ .Values.api.elb.id | quote }}
    kubernetes.io/elb.class: {{ .Values.api.elb.class | default "union" | quote }}
  {{- end }}
spec:
  type: {{ .Values.api.serviceType }}
  selector:
    app: lakeon-api
  ports:
    - name: https
      port: {{ if and .Values.api.elb .Values.api.elb.port }}{{ .Values.api.elb.port }}{{ else }}{{ .Values.api.port | default 8080 }}{{ end }}
      targetPort: http
    - name: http-internal
      port: {{ .Values.api.internalPort | default 8088 }}
      targetPort: {{ if .Values.api.ssl.enabled }}http-internal{{ else }}http{{ end }}
