{{- if include "lakeon.dataPlaneEnabled" . }}
apiVersion: v1
kind: Service
metadata:
  name: storage-controller
  namespace: {{ .Values.global.namespace }}
  labels:
    app: storage-controller
    {{- include "lakeon.labels" . | nindent 4 }}
spec:
  selector:
    app: storage-controller
  ports:
    - port: 1234
      targetPort: 1234
      name: http
{{- end }}
