apiVersion: v1
kind: Service
metadata:
  name: safekeeper
  namespace: {{ .Values.global.namespace }}
  labels:
    app: safekeeper
    {{- include "lakeon.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app: safekeeper
  ports:
    - name: pg
      port: {{ .Values.safekeeper.pgPort }}
      targetPort: pg
    - name: http
      port: {{ .Values.safekeeper.httpPort }}
      targetPort: http
