{{- if include "lakeon.dataPlaneEnabled" . }}
apiVersion: v1
kind: Service
metadata:
  name: storage-broker
  namespace: {{ .Values.global.namespace }}
  labels:
    app: storage-broker
    {{- include "lakeon.labels" . | nindent 4 }}
spec:
  selector:
    app: storage-broker
  ports:
    - name: grpc
      port: {{ .Values.storageBroker.port }}
      targetPort: grpc
{{- end }}
