# hwstaff data-plane CCE overrides.
# Use together with values.yaml:
#   helm ... -f values.yaml -f values-data-plane.yaml

plane:
  mode: data

api:
  replicas: 0
  serviceType: ClusterIP
  autoscaling:
    enabled: false

proxy:
  replicas: 2
  authEndpoint: ""
  lakeonDataProxy:
    enabled: true
    maxBackendsPerKey: 10
  projectInfoCache: "size=0,ttl=0s,max_roles=0,gc_interval=60m"
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 8
    targetCPUUtilizationPercentage: 65

pageserver:
  serviceType: LoadBalancer
  elb:
    id: ""
    class: "performance"
    autocreate: '{"type":"inner","name":"dbay-pageserver-inner-elb","l4_flavor_id":"ec6df27e-8ae9-45e3-828f-a6de45e3e109","available_zone":["cn-north-4a","cn-north-4c"]}'

admin:
  enabled: false

console:
  enabled: false
